name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  coverage:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master

        - uses: actions/setup-node@v1
          with:
            node-version: '12'

        - name: GitHub Action for Yarn
          uses: Borales/actions-yarn@v2.1.0
          with:
            cmd: install

        - name: Test and publish code coverage
          uses: paambaati/codeclimate-action@v2.4.0
          env:
            CC_TEST_REPORTER_ID: ${{ secrets.CodeClimateReporterId }}
          with:
            coverageCommand: yarn coverage
            coverageLocations: "./coverage/clover.xml:clover"
            debug: true
