name: Lint

on:
  push:
    branches:
      - master
  pull_request:


jobs:
  # test:

  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Run ESLint
  #       uses: stefanoeb/eslint-action@1.0.2
  #     - name: Test & publish code coverage
  #       uses: paambaati/codeclimate-action@v2.4.0
  #       if: always()
  #       env:
  #         CC_TEST_REPORTER_ID: ${{ secrets.CodeClimateReporterId }}
  #         debug: true

  coverage:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master
        - uses: actions/setup-node@master
          with:
            node-version: '12'
        - run: npm install -g yarn
        - run: yarn install
        - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - run: chmod +x ./cc-test-reporter
        - run: CC_TEST_REPORTER_ID=${{ secrets.CodeClimateReporterId }} ./cc-test-reporter before-build --debug
        - run: yarn coverage
        - run: GIT_COMMIT_SHA=${GITHUB_SHA} GIT_BRANCH=${GITHUB_REF} CC_TEST_REPORTER_ID=${{ secrets.CodeClimateReporterId }} ./cc-test-reporter after-build --debug
