name: Lint

on: [pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run ESLint
        uses: stefanoeb/eslint-action@1.0.2
      - name: Run Jest
        uses: stefanoeb/jest-action@1.0.2
        if: always()
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.4.0
        if: always()
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CodeClimateReporterId }}